# Generated by Django 4.2.2 on 2023-08-16 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('övning_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fråga',
            name='Övning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='övning_app.övning'),
        ),
    ]
