# Generated by Django 4.2.2 on 2023-08-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('övning_app', '0002_alter_fråga_övning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativ',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choise', to='övning_app.fråga'),
        ),
    ]
