# Generated by Django 4.2.2 on 2023-08-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_question_question_description_img_and_more'),
        ('övning_app', '0003_alter_alternativ_question'),
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='all_questions_answered',
            field=models.ManyToManyField(blank=True, null=True, related_name='all_questions_answered', to='base.question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='besvarade_frågor',
            field=models.ManyToManyField(blank=True, null=True, related_name='besvarade_frågor', to='övning_app.fråga'),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_provläge_prov',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_provläge', to='base.prov'),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_provläge_quiz',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_provläge_quiz', to='base.prov'),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_questions',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_questions', to='base.question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='completed_quizzes',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_quizzes', to='base.quiz'),
        ),
        migrations.AlterField(
            model_name='user',
            name='correct_questions_answered',
            field=models.ManyToManyField(blank=True, null=True, related_name='correct_questions_answered', to='base.question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='done_quiz',
            field=models.ManyToManyField(blank=True, null=True, related_name='done_quiz', to='base.quiz'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gjorda_övningar',
            field=models.ManyToManyField(blank=True, null=True, related_name='gjorda_övningar', to='övning_app.övning'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pending_provs',
            field=models.ManyToManyField(blank=True, null=True, related_name='pending_provs', to='base.prov'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pending_quizzes',
            field=models.ManyToManyField(blank=True, null=True, related_name='pending_quizzes', to='base.quiz'),
        ),
        migrations.AlterField(
            model_name='user',
            name='påbörjade_övningar',
            field=models.ManyToManyField(blank=True, null=True, related_name='påbörjade_övningar', to='övning_app.övning'),
        ),
        migrations.AlterField(
            model_name='user',
            name='your_choise',
            field=models.ManyToManyField(blank=True, null=True, related_name='your_choise', to='base.choise'),
        ),
    ]
